### ISSUE TITLE
Which number pad should I press last? How to judge

### ISSUE THREAD

**Issue by ayou129** [Simonrak/writemask.it#3]
![image](https://github.com/user-attachments/assets/edd2c124-5264-40d7-8f4d-24497679ffb8)

**Comment by Simonrak** [comment]
Number of dwords. In this case it’s 3.

**Comment by ayou129** [comment]
Do you mean to look at the value between Table Offset/Table BIR?
Another question, what is the function of Writemasker?

**Comment by Simonrak** [comment]
A dword is 32-bit or in this example it’s 8 hexadecimals, there are 3 dwords In the image to the right. 

The writemask places a masking layer above the configuration space when using the shadow configuration in pcileech.

**Comment by ayou129** [comment]
Thanks bro
